### ISSUE TITLE
How do you test with a Personal Authorization Token?

### ISSUE THREAD

**Issue by albertyw** [uber/rides-python-sdk#18]
There's a section in the developer dashboard that allows you to generate a "personal access token."  How do you use that?  From [auth.py](https://github.com/uber/rides-python-sdk/blob/master/uber_rides/auth.py#L276), it seems the code only supports taking the full redirect url.

**Comment by christinekim** [comment]
You will actually not be using any of the logic in `auth.py` which is meant to help you get an access token by stepping through the OAuth flow.

You can generate an access token under the settings tab of your application in the developer dashboard (developer.uber.com) Use this access token to create a session, which can then be used to create an sdk client. 

This feature is actually really useful if you are just testing a few endpoints of the API for your own account. I would recommend generating a personal access token then using it to curl the API and see what sort of responses you get back.

If you are interested in using the Python SDK to interact with the API, going through the traditional OAuth flow is not difficult and may be easier than generating a token in the dashboard and copying it over to use in the SDK. I would suggest taking a look at the `authorization_code_grant.py` script in the `example` folder for how this is done. This way, you can automatically refresh the token when it expires and don't need to copy over a token from the dashboard.

**Comment by Perados** [comment]
@christinekim What about the `expires_in_seconds` parameter? I manage to instantiate a `OAuth2Credential` object using my Personal Access Token and a random `expires_in_seconds`, but I don't like it. What is the expiration time of a Personal Access Token and where can I see it?

**Comment by christinekim** [comment]
Currently, all of the data about the access token (such as expiration, refresh token, token type, what scopes were granted) is not displayed when you generate an access token for yourself through the developer dashboard. The feature just returns the access token so you can copy it and test the API for yourself.

All access tokens for our API expire in 30 days (2592000 seconds). If you step through the classic OAuth flow, you'll see that the response will look something like:

```
{
    "access_token": "xxx",
    "token_type": "Bearer",
    "expires_in": 2592000,
    "refresh_token": "xxx",
    "scope": "profile history"
}
```
