### ISSUE TITLE
Why can't be used in China

### ISSUE THREAD

**Issue by Lee-Kevin** [uber/rides-python-sdk#2]
I am a developer from China, why I can't use your SDK, If I need to modify, please tell me to change what

**Comment by christinekim** [comment]
Hi Kevin -- The SDK currently does not support China (API calls for riders based in China). You'll need to make some simple changes to the OAuth2 authorization url (login.uber.com --> login.uber.com.cn) and the API base url (api.uber.com --> api.uber.com.cn)

The changes are summarized here https://developer.uber.com/docs/china

Right now, you'll need to make these changes manually. Sorry about that! We are working on integrating this with the SDK so we can support China riders seamlessly :) Stay tuned!
