### ISSUE TITLE
I'm trying to test the uber signon with Auth0..redirect uri issues..

### ISSUE THREAD

**Issue by sirvon** [uber/rides-python-sdk#22]
I'm attempting to connect my uber app with a Auth0 signon.
And allow my users to sign on using their uber accounts.

When setting up and then trying the integration, 
I received the attached error...

<img width="494" alt="screen shot 2016-08-12 at 12 24 30 pm" src="https://cloud.githubusercontent.com/assets/1570089/17635274/4915915a-608b-11e6-95dc-7578944d319c.png">

I see this is the link that is being activated when pressing the try button within Auth0:

```bash
https://teamxna2.auth0.com/authorize/?response_type=code&scope=openid%20profile&client_id=aC7p8ZN4QVaBSq0HrQCa83yHBiAEhYoF&connection=uber&redirect_uri=https://manage.auth0.com/tester/callback?connection=uber
```

So in the Uber App dashboard I changed my redirect uri to variations of...
```bash
https://manage.auth0.com/tester/callback?connection=uber
https://manage.auth0.com/tester/callback
https://manage.auth0.com
```

But i'm still recieving errors...What should put as the redirect URI in uber dash
to try this integration?

thanks!

**Comment by christinekim** [comment]
Hi @sirvon, the redirect link you activate contains `teamxna2` in it, but the ones you have registered have `manage`. Have you tried switching that out?

**Comment by sirvon** [comment]
perfect!
