### ISSUE TITLE
end_latitude/end_longitude in Python SDK require?

### ISSUE THREAD

**Issue by hoangphuong** [uber/rides-python-sdk#3]
I see end_latitude/end_longitude in request car API is optional.
But in Python SDK, it is require? 
And tell me how to use user token in Python SDK.
Thanks!

**Comment by Rulikkk** [comment]
I am really interested in this detail too.

To be clear, there's some misprinting in docs. Here https://developer.uber.com/docs/v1-requests it says that either `Either this (end_latitude) or end_place_id must be specified.` (and what is `end_place_id`?)

In python API trip end coordinates look to be required.

In Uber native app, we can ask for a car without specifying destination.

Is it true that via API requests — end destination is required?

**Comment by hoangphuong** [comment]
Thanks!
I didn't use Python SDK.
I am using REST API, it work for me.
curl -v -H "Authorization: Bearer B7j3KOo8GKbnlUT56MO1Zc4xUaUy5e3xuF-bLlMfg" \
     -H "Content-Type: application/Jon" -X POST -d \ '{"start_latitude":"37.77703","start_longitude":"-122.419571"}' \
https://sandbox-api.uber.com/v1/requests

**Comment by christinekim** [comment]
This has been incorporated into our newest release, 0.2.0
