### ISSUE TITLE
API estimate response is different from the app

### ISSUE THREAD

**Issue by the1plummie** [uber/rides-python-sdk#30]
So i'm using following API call to get fare estimate:
```
response = api_client.estimate_ride(
        product_id=products[0].get('product_id'),
        start_latitude=home['lat'],
        start_longitude=home['long'],
        end_latitude=work['lat'],
        end_longitude=work['long'],
        seat_count=1
    )
```
the price in the response is different from what's shown on the actual Uber app. Why the discrepancy? Is this intentional? 
Thanks.

**Comment by agraebe** [comment]
@the1plummie the API estimates should be in the same range as the Uber app estimates. There are some minor exceptions to this case, e.g. when some cities run promotions for specific Uber products. Could you provide a bit more details please to help reproduce the error:
- Time of the API call and time of the Uber app estimate check
- Uber app version
- The exact location (lat, lon) and the exact product_id
- The API response and app estimate

**Comment by the1plummie** [comment]
I checked just a few minutes ago, the difference is within 5c... but last night the difference is $2+ for uber pool. Not sure if something weird last night.
app ver: v3.219.12

If I see same issue again i'll post more details.
Thanks.
