### ISSUE TITLE
Is there a way to apply promocode using SDK?

### ISSUE THREAD

**Issue by BakanovKirill** [uber/rides-python-sdk#34]
curl -X PATCH -H "Authorization: Bearer <TOKEN>" \
  -H "Content-Type: application/json" \
  -d '{
    "applied_promotion_codes": "mypromo"
  }' "https://api.uber.com/v1.2/me"

Is this function existing?

I didn't find anything related to **applied_promotion_codes** in the sources

**Comment by dustinwhittle** [comment]
Hi,

We do not currently support this endpoint in the sdk, but we will note it as a feature request. You can access the underlying request library using the api client:

`client._api_call('PATCH', 'v1.2/me', { 'applied_promotion_codes': 'xxx' })`

**Comment by dustinwhittle** [comment]
I haven't implemented and tested yet, but 9ef271eaa9df2973590a3067ad2360d6d2cb68de should work.

**Comment by BakanovKirill** [comment]
thanks. It works. I used requests library before you answered me, bu this approach looks nicer.

**Comment by BakanovKirill** [comment]
Also is there a way to revert applying promocode? Cause i can't test it without buying real events. (And i don't wanna make mocks because API can change)

**Comment by dustinwhittle** [comment]
There is not currently a way to remove a promo code from a rider account.

**Comment by dustinwhittle** [comment]
Merged to master and resolved. I will release a new sdk version with more updated next week.
