### ISSUE TITLE
OAuth 2.0 Credentials Refreshing Issue

### ISSUE THREAD

**Issue by AmandaBeuno** [uber/rides-python-sdk#42]
Thank you for the great SDK. Totally appreciated!

I tried the simple example in the rides-python-sdk and I added the needed information in the "config.yaml" file and I got the right credentials in the "oauth2_session_store.yaml".  I managed to request a ride with sandbox enabled and everything works like a charm.

Problem is 4 to 5 days later when I try to request a ride, I get 401: Invalid OAuth 2.0 credentials provided. 

Under the "Authorization" section in the README.rst file it is stated that 

> The SDK will handle the token refresh for you automatically when it makes API requests with an UberRidesClient.

Am I missing any steps that I am not aware of ? or is this an issue with the example ?

Thank you again for your great effort providing a python SDK for Uber.

**Comment by dustinwhittle** [comment]
The token refresh is not supported in the example. If you remove the oauth2_session_store.yaml and auth again it will work as expected.
