### ISSUE TITLE
Unable to authenticate session with server token

### ISSUE THREAD

**Issue by ussumant** [uber/rides-python-sdk#43]
`from uber_rides.session import Session`
`session = Session(server_token= TOKEN )`

Returns error of invalid syntax.

**Comment by Subzidion** [comment]
Have you defined TOKEN with a server_token? You can create an application on the [Developer Dashboard](https://developer.uber.com/dashboard/) which will give you a server token to use.

**Comment by ussumant** [comment]
Yes. I have inputed the Server token of my application from the developer dashboard in place of `TOKEN`
