### ISSUE TITLE
Python 3.x: invalid exception handing syntax

### ISSUE THREAD

**Issue by denismakogon** [uber/rides-python-sdk#5]
`    except (ClientError, UberIllegalState), error:
        fail_print(error)
        return`

Given syntax is invalid in Python 3.x. Only next syntax is allowed
`    except (ClientError, UberIllegalState) as error:
        fail_print(error)
        return`

**Comment by christinekim** [comment]
Fixed with https://github.com/uber/rides-python-sdk/pull/9
