### ISSUE TITLE
how to get redirect_url in python script directly instead of copying url from browser

### ISSUE THREAD

**Issue by MeghaVaishy** [uber/rides-python-sdk#51]

**Comment by ALERTua** [comment]
https://github.com/uber/rides-python-sdk/blob/master/example/rider_dashboard.py
Flask example will help you.

**Comment by MeghaVaishy** [comment]
redirect(auth_flow.get_authorization_url()) results sign in page of uber want to automate that process for creating bot using its rides api so that i'll directly get redirect_url at final . How shall i do that can u please suggest me .

**Comment by ALERTua** [comment]
as I can imagine, you cannot get user authorization without an authorization process.

**Comment by MeghaVaishy** [comment]
Hi , the redirect(auth_flow.get_authorization_url()) results the sign in of uber page 

https://auth.uber.com/login/?next_url=https%3A%2F%2Flogin.uber.com%2Foauth%2Fv2%2Fauthorize%3Fclient_id%3DxU2nGfB0FJohaD7z3cnPOgpQrdrsMPwg%26redirect_uri%3Dhttps%253A%252F%252Fbotforuber.herokuapp.com%252Fredirect_uri%26response_type%3Dcode%26scope%3DREQUEST%26state%3DlAKPPlOegIqK57Cpj3gIDigYXtVZG7Re&state=PmPxUD36AVUQyQWb6IrQYWToh_jSh40fC6eKr6p0hpk%3D   

Want to automate that process
