### ISSUE TITLE
Python 3.5: Switch from requests to aiohttp

### ISSUE THREAD

**Issue by denismakogon** [uber/rides-python-sdk#8]
In order to make library more desirable to be integrated into existing or new solution based on Python 3.5 (released on April 2015) it is necessary to switch into aiohttp lib that applies async paradigm of coroutines to HTTP workflows.

**Comment by christinekim** [comment]
I will look into the suggestion for [aiohttp](https://github.com/KeepSafe/aiohttp) lib, thanks @denismakogon. I would like to add asynchronous support for this library, and am also considering supporting [tornado](https://github.com/tornadoweb/tornado) applications.

I would like to add asynchronous support soon, but am not actively working on a solution right now. Will update here when that changes.

**Comment by denismakogon** [comment]
@christinekim tornado is complicated for developing and supporting, aiohttp is the best one for async HTTP workflows.

**Comment by Subzidion** [comment]
If you want to continue to support Python 2, aiohttp won't be an option because it requires 3.4.1+. If there is still interest, I can look into something like tornado if you want to continue Python 2 support, otherwise I can give aiohttp a shot.

**Comment by dustinwhittle** [comment]
I think the best direction is to add async support using tornado. We are not actively working on supporting async in the sdk, so a pr using tornado would be welcomed. While I think aiohttp/asyncio is ideal, we need to support Python 2/3.

**Comment by dustinwhittle** [comment]
Closing as there is not currently a plan to offer an async implementation. An async implementation can be accomplished with existing sdk using gevent or tornado.
